### ISSUE TITLE
sfn update throwing strange errors

### ISSUE THREAD

**Issue by jamesla** [sparkleformation/sfn#267]
When trying to update my stack (using sfn 3.0.26) I am getting the following error (but the stack still deploys fine):

```
[I] 09:01:46 ➜  sparkleformation git:(pipeline_yml) ✗ sfn update buildkite-ci-dev --file master.rb --debug
[Sfn]: SparkleFormation: update
[Sfn]:   -> Name: buildkite-ci-dev Path: /home/vagrant/Documents/buildkite-ci/sparkleformation/master.rb
[Sfn]: Pre-update resource planning report:

  Update plan for: buildkite-ci-dev > Buildkite > BuildkiteLightCloudformationStack
    No resource lifecycle changes detected!


  Update plan for: buildkite-ci-dev > Buildkite > BuildkiteHeavyCloudformationStack
    No resource lifecycle changes detected!


  Update plan for: buildkite-ci-dev > Buildkite
    No resource lifecycle changes detected!


  Update plan for: buildkite-ci-dev > Container
    No resource lifecycle changes detected!


  Update plan for: buildkite-ci-dev
    No resource lifecycle changes detected!

[Sfn]: Apply this stack update? (Y/N): y
[Sfn]: Events for Stack: buildkite-ci-dev
I, [2017-09-01T09:19:38.310555 #24077]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x0055ebcaf95e78>)
I, [2017-09-01T09:19:38.593524 #24077]  INFO -- : Stack list has been updated from upstream and cached locally
ERROR: NoMethodError: undefined method `map' for nil:NilClass
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:80:in `block in get_events'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:65:in `map'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:65:in `get_events'
/var/lib/gems/2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:24:in `block (3 levels) in execute!'
/var/lib/gems/2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:56:in `table'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:23:in `block (2 levels) in execute!'
/var/lib/gems/2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `instance_exec'
/var/lib/gems/2.4.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `display'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:40:in `block in execute!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:21:in `execute!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command_module/base.rb:129:in `poll_stack'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/update.rb:146:in `block in execute!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/lib/sfn/command/update.rb:143:in `execute!'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/bin/sfn:52:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.4.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/var/lib/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/var/lib/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/var/lib/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/var/lib/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/var/lib/gems/2.4.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/var/lib/gems/2.4.0/gems/sfn-3.0.26/bin/sfn:14:in `<top (required)>'
/usr/local/bin/sfn:22:in `load'
/usr/local/bin/sfn:22:in `<main>'
```

I noticed that this bug had been fixed in the master branch (3.0.27) so I built the latest version of sfn and it gets to the same point but gets into an infinite loop spitting out the following error:

```
I, [2017-08-31T23:20:51.538511 #1]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x00000002239e78>)
I, [2017-08-31T23:20:51.788372 #1]  INFO -- : Stack list has been updated from upstream and cached locally
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
[ERROR]: Unexpected error received fetching events: can't modify frozen Bogo::Smash
```

I'm really hoping to get CD working so need to get these errors resolved that I have lived with for a while, has anybody else experienced this and is there a solution currently?

**Comment by chrisroberts** [comment]
This should be resolved in the latest release. Cheers!

**Comment by jamesla** [comment]
@chrisroberts thanks but I have just tested and this is not fixed on version 28 or 29 - so should probably be reopened.

**Comment by jamesla** [comment]
@chrisroberts I found that the issue is the gemfile dependencies isn't forcing an update to the new version of miasma-aws that resolved this so should be an easy fix.
